name: Deploy PR Preview

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [master]

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true
          
      - name: Build Jekyll site
        run: bundle exec jekyll build --destination _site
        
      - name: Deploy to preview
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          destination_dir: pr-${{ github.event.number }}
          keep_files: true
          
      - name: Comment PR with preview link
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            ## 🚀 Preview Deployed Successfully
            
            **Preview URL:** https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/pr-${{ github.event.number }}/
            
            ### What's included in this preview:
            - ✅ Phase 1: Astro-compatible directory structure
            - ✅ All Jekyll functionality preserved
            - ✅ Static assets moved to public/ directory
            - ✅ Sass files reorganized for Astro compatibility
            
            This preview will be automatically updated when you push new commits to this PR.
            
            ---
            
            **Testing checklist:**
            - [ ] Homepage loads correctly
            - [ ] Blog posts display properly  
            - [ ] Images load from correct paths
            - [ ] Navigation works as expected
            - [ ] Styles apply correctly
            - [ ] All links function properly